List categoryList = [
  "Academic",
      "AC Serviceman",
      "Accountant",
      "Activist",
      "Actor",
      "Actuarial",
      "Administrative",
      "Advertising",
      "Agent",
      "Agricultural",
      "Analyst",
      "Animal-Trainer",
      "Animator",
      "Anarchist",
      "Angel Investor",
      "Apprentice",
      "App Developer",
      "Artist",
      "Art Director",
      "Architect",
      "Assemblyman",
      "Auditor",
      "Aviation",
      "Babysitter",
      "Barber",
      "Blacksmith",
      "Blogger",
      "Boom Operator",
      "Bored",
      "Boxer",
      "Businessman",
      "Cameraman",
      "Car Dealer",
      "Carpenter",
      "Casting Director",
      "Caterer",
      "Chef",
      "Chiropractor",
      "Cinematographer",
      "Civil Servant",
      "Cleaner",
      "Conductor",
      "Consulting",
      "Construction",
      "Contractor",
      "Comedian",
      "Composer",
      "Computer Scientist",
      "Computer Security Analyst",
      "Content Creator",
      "CopyWriter",
      "Cosmetologist",
      "Counselor",
      "Clearing-Agent",
      "Clerk",
      "Cobbler",
      "Crimnologist",
      "Critic",
      "CEO",
      "CULTURAL",
      "Cybersecurity",
      "DJ",
      "Dancer",
      "Data Scientist",
      "Data Analyst",
      "Delivery man",
      "Doctor",
      "Dog Trainer",
      "Documentarian",
      "DESIGNER",
      "D.O.P.",
      "DRIVER",
      "Economist",
      "eCurrency Trader",
      "Editor",
      "EDITORIAL",
      "Electrician",
      "ENERGY",
      "ENGINEER",
      "Enterpreneur",
      "Event-Planner",
      "Exterminator",
      "FASHION",
      "Fashion Designer",
      "FILM",
      "FILMMAKER",
      "FINANCIAL",
      "Fisherman",
      "Florist",
      "Foley Artist",
      "Food Seller",
      "Forex Trader",
      "Footballer",
      "FREELANCE",
      "Game Developer",
      "Gamer",
      "Gardener",
      "Geographer",
      "Geologist",
      "Gun Instructor",
      "GunSmith",
      "Gun-Dealer",
      "Graphic Designer",
      "Hacker",
      "Hair Dresser",
      "Handyman",
      "Historian",
      "Horticulturist",
      "Hospitality",
      "House-Help",
      "Humanitarian",
      "Hunter",
      "Illustrator",
      "Influencer",
      "Information Broker",
      "Instructor",
      "Interior-Decorator",
      "INDUSTRIAL",
      "Inspector",
      "I.T.",
      "IT-Technician",
      "Janitor",
      "Journalist",
      "JUDICIAL",
      "Land Surveyor",
      "LANGUAGES",
      "Lawyer",
      "Labourer",
      "Lab Tech",
      "LEGAL",
      "Librarian",
      "Life Guard",
      "LoanShark",
      "Lobbyist",
      "Maid",
      "MC",
      "Makeup Artist",
      "MANAGER",
      "Manicurist",
      "Marketer",
      "MARKETING",
      "Masseuse",
      "Mate",
      "Martial-Arts Instructor",
      "Mason",
      "MECHANIC",
      "MEDIC",
      "MEDICAL",
      "Meteorologist",
      "Midwife",
      "Mini Truck Driver",
      "Mining",
      "Minister(Senator)",
      "Model",
      "Motion Graphics",
      "Member of Parliament(MP)",
      "Musician",
      "Music Band",
      "Music Instructor",
      "Nanny",
      "Narrator",
      "Network Administrator",
      "NEWS",
      "Nurse",
      "Nutritionist",
      "Oculist",
      "Oncologist",
      "Painter",
      "Pastor",
      "Pediatrician",
      "Pedicurist",
      "Pet Groomer",
      "Pet Walker",
      "Pharmacist",
      "Pilot",
      "Pirate",
      "Playboy",
      "Plumber",
      "Police",
      "Photographer",
      "Politician",
      "Private Investigator",
      "Priest",
      "Property-Agent",
      "Producer",
      "Producer(Film)",
      "Producer(Music)",
      "Programmer",
      "Physiotherapist",
      "Psychologist",
      "Psychiatrist",
      "Presenter",
      "Realtor",
      "Rapper",
      "Renter",
      "Researcher",
      "Repairer",
      "Representative",
      "SALES",
      "Satellite TV Installer",
      "Security",
      "Seller",
      "Set Designer",
      "Student",
      "Sportsman",
      "Scientist",
      "Secretary",
      "Stylist",
      "Surgeon",
      "StockBroker",
      "Set-Designer",
      "Surgeon",
      "Sprayer",
      "Social Media",
      "Social Worker",
      "Sound Engineer",
      "Seamstress",
      "Spoken Wordist",
      "Sportsman",
      "Statistician",
      "Steelbender",
      "Steward",
      "Studies Teacher",
      "Stock Broker",
      "Stylist",
      "Swimming Instructor",
      "System Administrator",
      "System Designer",
      "Tailor",
      "Talent Hunter",
      "Tattoist",
      "Teacher",
      "Technician",
      "Telecom",
      "Television",
      "Therapist",
      "Tiler",
      "Trader",
      "Translator",
      "Trainer",
      "TRANSPORTATION",
      "Trash-Collector",
      "TOURiSM",
      "Tow-Truck Driver",
      "Truck Driver",
      "TV Personality",
      "TV Presenter",
      "Tycoon",
      "Unemployed",
      "Upcoming Artiste",
      "UX Designer",
      "Vetenarian",
      "VFX",
      "Videographer",
      "Virulogist",
      "Video Editor",
      "Voice Over(Narrator)",
      "Voice Trainer",
      "Vulcanizer",
      "Waiter",
      "Wants a Car",
      "Wants Charity",
      "Wants Employment",
      "Wants Accomodation",
      "Wants Relationship (Male)",
      "Wants Relaitonship (Female)",
      "Watchman",
      "Web Developer",
      "Web Designer",
      "Weaver",
      "Welder",
      "Writer",
      "Zoologist",
];